# Generated by Django 2.2 on 2020-08-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200818_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pet_age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_temperament',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
