# Generated by Django 2.2 on 2020-08-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200819_0826'),
        ('dashboard', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post', to='login.User'),
        ),
    ]
